.class public final LGf/n$a$i;
.super Lkotlin/jvm/internal/m;
.source "SourceFile"

# interfaces
.implements Lwf/a;


# annotations
.annotation system Ldalvik/annotation/EnclosingMethod;
    value = LGf/n$a;-><init>(LGf/n;)V
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = null
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lkotlin/jvm/internal/m;",
        "Lwf/a<",
        "LMf/e;",
        ">;"
    }
.end annotation


# instance fields
.field public final synthetic a:LGf/n;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "LGf/n<",
            "TT;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(LGf/n;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "LGf/n<",
            "TT;>;)V"
        }
    .end annotation

    iput-object p1, p0, LGf/n$a$i;->a:LGf/n;

    const/4 p1, 0x0

    invoke-direct {p0, p1}, Lkotlin/jvm/internal/m;-><init>(I)V

    return-void
.end method


# virtual methods
.method public final invoke()Ljava/lang/Object;
    .locals 4

    sget v0, LGf/n;->d:I

    iget-object p0, p0, LGf/n$a$i;->a:LGf/n;

    invoke-virtual {p0}, LGf/n;->v()Llg/b;

    move-result-object v0

    iget-object v1, p0, LGf/n;->c:LGf/Y$b;

    invoke-virtual {v1}, LGf/Y$b;->invoke()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, LGf/n$a;

    invoke-virtual {v1}, Ljava/lang/Object;->getClass()Ljava/lang/Class;

    sget-object v2, LGf/s$a;->b:[LDf/k;

    const/4 v3, 0x0

    aget-object v2, v2, v3

    iget-object v1, v1, LGf/s$a;->a:LGf/Y$a;

    invoke-virtual {v1}, LGf/Y$a;->invoke()Ljava/lang/Object;

    move-result-object v1

    const-string v2, "<get-moduleData>(...)"

    invoke-static {v1, v2}, Lkotlin/jvm/internal/k;->e(Ljava/lang/Object;Ljava/lang/String;)V

    check-cast v1, LRf/h;

    iget-boolean v2, v0, Llg/b;->c:Z

    iget-object v1, v1, LRf/h;->a:Lyg/k;

    if-eqz v2, :cond_0

    invoke-virtual {v1, v0}, Lyg/k;->b(Llg/b;)LMf/e;

    move-result-object v0

    goto :goto_0

    :cond_0
    iget-object v1, v1, Lyg/k;->b:LMf/B;

    invoke-static {v1, v0}, LMf/t;->a(LMf/B;Llg/b;)LMf/e;

    move-result-object v0

    :goto_0
    if-nez v0, :cond_3

    iget-object p0, p0, LGf/n;->b:Ljava/lang/Class;

    invoke-static {p0}, LRf/d$a;->a(Ljava/lang/Class;)LRf/d;

    move-result-object v0

    if-eqz v0, :cond_1

    iget-object v0, v0, LRf/d;->b:Lfg/a;

    if-eqz v0, :cond_1

    iget-object v0, v0, Lfg/a;->a:Lfg/a$a;

    goto :goto_1

    :cond_1
    const/4 v0, 0x0

    :goto_1
    if-nez v0, :cond_2

    const/4 v1, -0x1

    goto :goto_2

    :cond_2
    sget-object v1, LGf/n$b;->a:[I

    invoke-virtual {v0}, Ljava/lang/Enum;->ordinal()I

    move-result v2

    aget v1, v1, v2

    :goto_2
    packed-switch v1, :pswitch_data_0

    :pswitch_0
    new-instance p0, Lhf/h;

    invoke-direct {p0}, Ljava/lang/RuntimeException;-><init>()V

    throw p0

    :pswitch_1
    new-instance v1, LGf/W;

    new-instance v2, Ljava/lang/StringBuilder;

    const-string v3, "Unknown class: "

    invoke-direct {v2, v3}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const-string p0, " (kind = "

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const/16 p0, 0x29

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    invoke-direct {v1, p0}, LGf/W;-><init>(Ljava/lang/String;)V

    throw v1

    :pswitch_2
    new-instance v0, Ljava/lang/UnsupportedOperationException;

    const-string v1, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It\'s not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: "

    invoke-static {p0, v1}, LE5/a;->d(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v0

    :pswitch_3
    new-instance v0, Ljava/lang/UnsupportedOperationException;

    const-string v1, "Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: "

    invoke-static {p0, v1}, LE5/a;->d(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v0

    :pswitch_4
    new-instance v0, LGf/W;

    const-string v1, "Unresolved class: "

    invoke-static {p0, v1}, LE5/a;->d(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, LGf/W;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_3
    return-object v0

    nop

    :pswitch_data_0
    .packed-switch -0x1
        :pswitch_4
        :pswitch_0
        :pswitch_3
        :pswitch_3
        :pswitch_3
        :pswitch_2
        :pswitch_1
        :pswitch_4
    .end packed-switch
.end method
